apiVersion: v2
name: labyrinth-vienna-site
version: 0.1.0
kubeVersion: ">= 1.14.0-0"
description: Example Helm chart.
type: application
keywords:
- example
- template
home: https://opensource.cze.tech/labyrinth-vienna-site
sources:
- https://github.com/czetech/labyrinth-vienna-site
maintainers:
- name: Petr Czepiec
  email: petr@czepiec.me
  url: https://czepiec.me/
appVersion: 0.1.1
