{{- if .Values.healthCheckPolicy.enabled -}}
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ include "labyrinth-vienna-site.fullname" . }}
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /navody
  targetRef:
    group: ""
    kind: Service
    name: {{ include "labyrinth-vienna-site.fullname" . }}-http
{{- end }}
