apiVersion: v1
kind: Service
metadata:
  name: {{ include "labyrinth-vienna-site.fullname" . }}-http
  annotations:
    {{- toYaml .Values.http.service.annotations | nindent 4 }}
  labels:
    {{- include "labyrinth-vienna-site.labels" . | nindent 4 }}
    app.kubernetes.io/component: http
spec:
  ports:
  - name: http
    nodePort: {{ toYaml .Values.http.service.nodePort }}
    port: {{ toYaml .Values.http.service.port }}
    protocol: TCP
    targetPort: http
  selector:
    {{- include "labyrinth-vienna-site.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: http
  type: {{ toYaml .Values.http.service.type }}
