apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "labyrinth-vienna-site.fullname" . }}-http
  annotations:
    {{- toYaml .Values.http.annotations | nindent 4 }}
  labels:
    {{- include "labyrinth-vienna-site.labels" . | nindent 4 }}
    app.kubernetes.io/component: http
spec:
  replicas: {{ toYaml .Values.http.replicas }}
  selector:
    matchLabels:
      {{- include "labyrinth-vienna-site.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: http
  template:
    metadata:
      annotations:
        {{- toYaml .Values.http.podAnnotations | nindent 8 }}
      labels:
        {{- include "labyrinth-vienna-site.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: http
    spec:
      affinity:
        {{- toYaml .Values.http.affinity | nindent 8 }}
      containers:
      - name: app
        env:
        - name: DATABASE_URL
          value: {{ toYaml .Values.databaseUrl }}
        image: {{ .Values.image.repository }}:{{ if .Values.image.tag }}{{ .Values.image.tag }}{{ else }}{{ .Chart.AppVersion }}{{ end }}
        imagePullPolicy: {{ toYaml .Values.image.pullPolicy }}
        lifecycle:
          {{- toYaml .Values.http.lifecycle | nindent 10 }}
        ports:
        - name: app
          containerPort: 4321
        resources:
          {{- toYaml .Values.http.resources | nindent 10 }}
      - name: nginx
        image: nginx:1.27-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.http.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.http.tolerations | nindent 8 }}
      volumes:
      - name: nginx-config
        configMap:
          name: {{ include "labyrinth-vienna-site.fullname" . }}-nginx
